In [1]:
import numpy as np
from pymatgen.core.structure import Structure
from pymatgen.io.vasp.inputs import Poscar

def create_root7_supercell(poscar_file='POSCAR1.vasp', output_file='POSCAR_root7', matrix_type=1):
    """
    Create a √7×√7 supercell from a hexagonal POSCAR file with different matrix options.
    
    Args:
        poscar_file (str): Input POSCAR filename
        output_file (str): Output POSCAR filename
        matrix_type (int): Which transformation matrix to use (1-2)
    """
    # Load the original structure
    structure = Structure.from_file(poscar_file)
    
    # Verify the structure is hexagonal
    a, b, c = structure.lattice.abc
    alpha, beta, gamma = structure.lattice.angles
    if not (abs(a - b) < 0.1 and abs(gamma - 120) < 1):
        print("Warning: The input structure doesn't appear to be hexagonal (a ≈ b, γ ≈ 120°)")
    
    # Define valid √7×√7 transformation matrices with determinant exactly 7
    matrices = {
        1: np.array([[1, 3, 0], [-3, -2, 0], [0, 0, 1]]),  # det = (1*-2) - (3*-3) = -2 + 9 = 7
        2: np.array([[3, 1, 0], [-1, 2, 0], [0, 0, 1]]),   # det = (3*2) - (1*-1) = 6 + 1 = 7
        3: np.array([[2, -1, 0], [3, 2, 0], [0, 0, 1]]),   # det = (2*2) - (-1*3) = 4 + 3 = 7
        4: np.array([[2, 3, 0], [-1, 2, 0], [0, 0, 1]])    # det = (2*2) - (3*-1) = 4 + 3 = 7
    }
    
    # Get the selected transformation matrix
    if matrix_type not in matrices:
        raise ValueError("matrix_type must be between 1 and 4")
    transformation = matrices[matrix_type]
    
    # Create the supercell
    supercell = structure.copy()
    supercell.make_supercell(transformation)
    
    # Write the new POSCAR
    poscar = Poscar(supercell)
    poscar.write_file(output_file)
    
    print(f"√7×√7 supercell created with {len(supercell)} atoms using matrix type {matrix_type}.")
    print(f"Transformation matrix:\n{transformation}")
    print(f"New POSCAR written to: {output_file}")

if __name__ == "__main__":
    # Example usage with different matrix types
    for i in range(1, 5):
        create_root7_supercell(output_file=f'POSCAR_root7_type{i}', matrix_type=i)

√7×√7 supercell created with 14 atoms using matrix type 1.
Transformation matrix:
[[ 1  3  0]
 [-3 -2  0]
 [ 0  0  1]]
New POSCAR written to: POSCAR_root7_type1
√7×√7 supercell created with 14 atoms using matrix type 2.
Transformation matrix:
[[ 3  1  0]
 [-1  2  0]
 [ 0  0  1]]
New POSCAR written to: POSCAR_root7_type2
√7×√7 supercell created with 14 atoms using matrix type 3.
Transformation matrix:
[[ 2 -1  0]
 [ 3  2  0]
 [ 0  0  1]]
New POSCAR written to: POSCAR_root7_type3
√7×√7 supercell created with 14 atoms using matrix type 4.
Transformation matrix:
[[ 2  3  0]
 [-1  2  0]
 [ 0  0  1]]
New POSCAR written to: POSCAR_root7_type4
